version: "3"
services:
  dev:
    user: node
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ..:/workspace:delegated
      - node_modules:/workspace/node_modules
      - cache:/workspeace/.cache

    ports:
      - 8000
    environment:
      - LANG=C.UTF-8
    command: ["sleep", "infinity"]

volumes:
  node_modules:
  cache:
